apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-container
  template:
    metadata:
      labels:
        app: web-app-container
    spec:
      containers:
      - name: my-app
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: mongo-username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: my-app-config-map
              key: mongo-endpoint

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: web-app-container
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010